#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

from _demo_corpus_common import CORPUS_ROOT, manifest_record, relative_to_corpus, sha256_file, write_jsonl


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate lightweight demo video keyframes and transcript placeholders.")
    parser.add_argument("--output-dir", type=Path, default=CORPUS_ROOT / "samples_generated")
    parser.add_argument("--manifest-out", type=Path, default=CORPUS_ROOT / "manifests" / "demo_video_manifest.jsonl")
    parser.add_argument("--count", type=int, default=3)
    args = parser.parse_args()
    records = []
    for index in range(1, args.count + 1):
        frame_dir = args.output_dir / "video_keyframes"
        audio_dir = args.output_dir / "audio_transcripts"
        frame_dir.mkdir(parents=True, exist_ok=True)
        audio_dir.mkdir(parents=True, exist_ok=True)
        frame = frame_dir / f"person_video_keyframe_{index:03d}.png"
        transcript = audio_dir / f"transcript_sample_{index:03d}.txt"
        render_frame(frame, index)
        transcript.write_text(f"会议备忘 {index}: 本段为合成转写样本, 行动项是检查 Stage 10 release gate。\n", encoding="utf-8")
        records.append(
            manifest_record(
                asset_id=f"synthetic_video_keyframe_{index:03d}",
                local_rel=relative_to_corpus(frame),
                source="synthetic",
                source_url="project://digua/demo_corpus/video_keyframes",
                source_id=f"person_video_keyframe_{index:03d}",
                license_name="Synthetic Project-Owned",
                author="Digua AI-NAS project",
                attribution="Generated by generate_demo_videos.py",
                sha256=sha256_file(frame),
                modality="video",
                target_categories=["人物照片"],
                expected_yolo_labels=["person"],
                expected_queries=["找视频里有人的片段"],
                redistribution_allowed=True,
                release_package_includes_file=True,
                extra={"asset_kind": "keyframe_placeholder"},
            )
        )
        records.append(
            manifest_record(
                asset_id=f"synthetic_transcript_{index:03d}",
                local_rel=relative_to_corpus(transcript),
                source="synthetic",
                source_url="project://digua/demo_corpus/audio_transcripts",
                source_id=f"transcript_sample_{index:03d}",
                license_name="Synthetic Project-Owned",
                author="Digua AI-NAS project",
                attribution="Generated by generate_demo_videos.py",
                sha256=sha256_file(transcript),
                modality="audio",
                target_categories=["课程资料"],
                expected_ocr_terms=["会议", "备忘", "行动项"],
                expected_queries=["音频转写"],
                redistribution_allowed=True,
                release_package_includes_file=True,
                extra={"asset_kind": "transcript_placeholder"},
            )
        )
    write_jsonl(args.manifest_out, records)
    print(args.manifest_out)
    print(f"records={len(records)}")
    return 0


def render_frame(path: Path, index: int) -> None:
    image = Image.new("RGB", (960, 540), color=(235, 242, 245))
    draw = ImageDraw.Draw(image)
    draw.rectangle((390, 110, 570, 420), fill=(230, 232, 236), outline=(50, 60, 80), width=6)
    draw.ellipse((425, 70, 535, 180), fill=(210, 185, 160), outline=(50, 60, 80), width=5)
    draw.rectangle((395, 190, 565, 350), fill=(240, 240, 240), outline=(50, 60, 80), width=4)
    draw.text((40, 40), f"Synthetic keyframe {index}: person present", fill=(20, 30, 45))
    image.save(path)


if __name__ == "__main__":
    raise SystemExit(main())

