#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from _demo_corpus_common import CORPUS_ROOT, load_yaml, manifest_record, relative_to_corpus, sha256_file, write_jsonl


TEMPLATES = {
    "invoice": {
        "title": "地瓜 AI-NAS 合成发票样张",
        "folder": "invoices",
        "terms": ["发票", "金额", "日期", "合计"],
        "lines": [
            "发票号码: SYN-INV-{index:04d}",
            "购买方: 示例用户",
            "项目: S100P AI-NAS 部署服务",
            "日期: 2026-07-{day:02d}",
            "金额: {amount}.00 元",
            "合计: {amount}.00 元",
            "说明: 本文件为项目生成样张, 不含真实隐私信息。",
        ],
        "categories": ["票据发票"],
        "queries": ["这张票据里的金额和日期是什么？"],
    },
    "contract": {
        "title": "地瓜 AI-NAS 合成合同样张",
        "folder": "contracts",
        "terms": ["合同", "付款", "条款", "甲方", "乙方"],
        "lines": [
            "合同编号: SYN-CON-{index:04d}",
            "甲方: 示例甲方",
            "乙方: 示例乙方",
            "付款条款: 验收通过后 7 日内支付 {amount}.00 元。",
            "服务内容: S100P + NAS 本地 AI 资料整理。",
            "安全边界: 不启用删除或覆盖, 不上传私有原文到云端。",
        ],
        "categories": ["合同资料"],
        "queries": ["这份合同的付款条款是什么？"],
    },
    "course_note": {
        "title": "地瓜 AI-NAS 合成课程笔记",
        "folder": "course_notes",
        "terms": ["课程", "笔记", "作业", "考试"],
        "lines": [
            "课程: 本地 AI-NAS 产品工程",
            "笔记编号: SYN-NOTE-{index:04d}",
            "主题: 多模态索引、OCR/RAG、受控整理",
            "作业: 运行 release gate 并提交报告。",
            "考试重点: 权限边界、证据链、回滚。",
        ],
        "categories": ["课程资料"],
        "queries": ["查找课程资料和笔记"],
    },
    "screenshot_note": {
        "title": "地瓜 AI-NAS 合成截图资料",
        "folder": "screenshots",
        "terms": ["截图", "资料", "待办"],
        "lines": [
            "截图资料: SYN-SHOT-{index:04d}",
            "待办: 检查 Release package integrity。",
            "状态: 合成样张, 仅用于 OCR/RAG gate。",
        ],
        "categories": ["截图资料"],
        "queries": ["查找截图类资料"],
    },
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic synthetic OCR/RAG documents.")
    parser.add_argument("--recipe", type=Path, default=CORPUS_ROOT / "recipes" / "target_classes.yaml")
    parser.add_argument("--output-dir", type=Path, default=CORPUS_ROOT / "samples_generated")
    parser.add_argument("--manifest-out", type=Path, default=CORPUS_ROOT / "manifests" / "synthetic_docs_manifest.jsonl")
    args = parser.parse_args()

    recipe = load_yaml(args.recipe)
    documents = recipe.get("documents") or {}
    records = []
    for doc_type, config in documents.items():
        template = TEMPLATES.get(doc_type)
        if not template or not config.get("generated", False):
            continue
        count = int(config.get("min_count") or 1)
        for index in range(1, count + 1):
            amount = 1000 + index * 37
            day = 10 + (index % 18)
            lines = [template["title"]] + [line.format(index=index, amount=amount, day=day) for line in template["lines"]]
            base = f"{doc_type}_{index:03d}"
            out_dir = args.output_dir / template["folder"]
            out_dir.mkdir(parents=True, exist_ok=True)
            txt_path = out_dir / f"{base}.txt"
            png_path = out_dir / f"{base}.png"
            pdf_path = out_dir / f"{base}.pdf"
            txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            render_png(png_path, lines)
            render_pdf(pdf_path, lines)
            for path in (txt_path, png_path, pdf_path):
                records.append(
                    manifest_record(
                        asset_id=f"synthetic_{doc_type}_{index:03d}_{path.suffix[1:]}",
                        local_rel=relative_to_corpus(path),
                        source="synthetic",
                        source_url="project://digua/demo_corpus/synthetic_docs",
                        source_id=f"{doc_type}_{index:03d}",
                        license_name="Synthetic Project-Owned",
                        author="Digua AI-NAS project",
                        attribution="Generated by Digua demo_corpus/scripts/generate_synthetic_docs.py",
                        sha256=sha256_file(path),
                        modality="document",
                        target_categories=list(template["categories"]),
                        expected_ocr_terms=list(config.get("expected_ocr_terms") or template["terms"]),
                        expected_queries=list(template["queries"]),
                        fixture_only_for_ci=False,
                        redistribution_allowed=True,
                        release_package_includes_file=True,
                        extra={"document_type": doc_type, "paired_stem": base},
                    )
                )
    write_jsonl(args.manifest_out, records)
    print(args.manifest_out)
    print(f"records={len(records)}")
    return 0


def render_png(path: Path, lines: list[str]) -> None:
    image = Image.new("RGB", (1200, 800), color=(250, 250, 246))
    draw = ImageDraw.Draw(image)
    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 30)
        title_font = ImageFont.truetype("DejaVuSans.ttf", 42)
    except Exception:
        font = ImageFont.load_default()
        title_font = font
    y = 70
    draw.text((70, y), lines[0], fill=(20, 24, 30), font=title_font)
    y += 80
    for line in lines[1:]:
        draw.text((90, y), line, fill=(35, 39, 47), font=font)
        y += 54
    draw.rectangle((60, 60, 1140, 740), outline=(90, 100, 115), width=3)
    image.save(path)


def render_pdf(path: Path, lines: list[str]) -> None:
    pdf = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    pdf.setFont("Helvetica", 18)
    pdf.drawString(54, height - 72, lines[0])
    pdf.setFont("Helvetica", 12)
    y = height - 120
    for line in lines[1:]:
        pdf.drawString(72, y, line)
        y -= 28
    pdf.save()


if __name__ == "__main__":
    raise SystemExit(main())

