#!/usr/bin/env bash
set -u

MODEL_MANIFEST="release/configs/model_manifest.yaml"
ENV_OUT=""
JSON_OUT=""
DRY_RUN=1
STRICT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model-manifest) MODEL_MANIFEST="${2:-}"; shift 2 ;;
    --env-out) ENV_OUT="${2:-}"; shift 2 ;;
    --json-out) JSON_OUT="${2:-}"; shift 2 ;;
    --apply) DRY_RUN=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --strict) STRICT=1; shift ;;
    *) shift ;;
  esac
done

payload="$(python3 - <<PY
import json, os, pathlib, yaml
manifest_path = pathlib.Path("$MODEL_MANIFEST")
data = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
models = {}
blockers = []
warnings = []
for key, item in (data or {}).items():
    env = item.get("path_env")
    value = os.environ.get(env, "") if env else ""
    exists = pathlib.Path(value).exists() if value else False
    required = bool(item.get("required"))
    required_demo = bool(item.get("required_for_demo"))
    status = "ready" if exists else ("missing_required" if required else "degraded")
    if required and not exists and bool($STRICT):
        blockers.append(f"{key}_model_missing:{env}")
    elif required_demo and not exists:
        warnings.append(f"{key}_demo_model_missing:{env}")
    models[key] = {
        "name": item.get("name"),
        "path_env": env,
        "path_configured": bool(value),
        "exists": bool(exists),
        "required": required,
        "required_for_demo": required_demo,
        "status": status,
        "sha256_policy": item.get("sha256"),
    }
payload = {
    "ok": not blockers,
    "dry_run": bool($DRY_RUN),
    "model_weights_bundled": False,
    "models": models,
    "blockers": blockers,
    "warnings": warnings,
}
print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
PY
)"

if [[ "$DRY_RUN" == "0" && -n "$ENV_OUT" ]]; then
  mkdir -p "$(dirname "$ENV_OUT")"
  {
    echo "# Generated by configure_models.sh; paths only, no model weights."
    for name in DIGUA_QWEN_MODEL_DIR DIGUA_CLIP_MODEL_DIR DIGUA_YOLO_MODEL_PATH DIGUA_OCR_MODEL_DIR DIGUA_ASR_MODEL_DIR; do
      value="${!name:-}"
      [[ -n "$value" ]] && printf '%s=%q\n' "$name" "$value"
    done
  } > "$ENV_OUT"
fi

if [[ -n "$JSON_OUT" ]]; then mkdir -p "$(dirname "$JSON_OUT")"; printf '%s\n' "$payload" > "$JSON_OUT"; fi
printf '%s\n' "$payload"
python3 - <<PY
import json, sys
raise SystemExit(0 if json.loads('''$payload''').get('ok') else 1)
PY
