#!/usr/bin/env bash
set -u

MODEL_MANIFEST="release/configs/model_manifest.yaml"
ENV_OUT=""
JSON_OUT=""
DRY_RUN=1
STRICT=0
MODEL_MODE="${DIGUA_MODEL_MODE:-local}"
CLOUD_BASE_URL="${DIGUA_CLOUD_BASE_URL:-}"
CLOUD_MODEL="${DIGUA_CLOUD_MODEL:-}"
CLOUD_API_KEY_FILE="${DIGUA_CLOUD_API_KEY_FILE:-}"
ALLOW_INSECURE_CLOUD=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model-manifest) MODEL_MANIFEST="${2:-}"; shift 2 ;;
    --env-out) ENV_OUT="${2:-}"; shift 2 ;;
    --json-out) JSON_OUT="${2:-}"; shift 2 ;;
    --apply) DRY_RUN=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --strict) STRICT=1; shift ;;
    --model-mode) MODEL_MODE="${2:-}"; shift 2 ;;
    --cloud-base-url) CLOUD_BASE_URL="${2:-}"; shift 2 ;;
    --cloud-model) CLOUD_MODEL="${2:-}"; shift 2 ;;
    --cloud-api-key-file) CLOUD_API_KEY_FILE="${2:-}"; shift 2 ;;
    --allow-insecure-cloud-endpoint) ALLOW_INSECURE_CLOUD=1; shift ;;
    *) shift ;;
  esac
done

payload="$(DIGUA_CONFIG_MODEL_MODE="$MODEL_MODE" DIGUA_CONFIG_CLOUD_BASE_URL="$CLOUD_BASE_URL" DIGUA_CONFIG_CLOUD_MODEL="$CLOUD_MODEL" DIGUA_CONFIG_CLOUD_API_KEY_FILE="$CLOUD_API_KEY_FILE" python3 - <<PY
import json, os, pathlib
manifest_path = pathlib.Path("$MODEL_MANIFEST")
data = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
models = {}
blockers = []
warnings = []
model_mode = os.environ["DIGUA_CONFIG_MODEL_MODE"]
if model_mode not in {"local", "cloud"}:
    blockers.append(f"unsupported_model_mode:{model_mode}")
for key, item in (data or {}).items():
    env = item.get("path_env")
    value = os.environ.get(env, "") if env else ""
    path = pathlib.Path(value) if value else None
    path_type = item.get("path_type")
    exists = bool(path and path.exists())
    if exists and path_type == "file":
        exists = path.is_file()
    elif exists and path_type == "executable":
        exists = path.is_file() and os.access(path, os.X_OK)
    elif exists and path_type == "directory":
        exists = path.is_dir()
    required = bool(item.get("required")) and model_mode == "local"
    required_demo = bool(item.get("required_for_demo"))
    status = "ready" if exists else ("missing_required" if required else "degraded")
    if required and not exists and bool($STRICT):
        blockers.append(f"{key}_model_missing:{env}")
    elif required_demo and not exists:
        warnings.append(f"{key}_demo_model_missing:{env}")
    models[key] = {
        "name": item.get("name"),
        "path_env": env,
        "path_configured": bool(value),
        "exists": bool(exists),
        "required": required,
        "required_for_demo": required_demo,
        "status": status,
        "sha256_policy": item.get("sha256"),
        "path_type": path_type,
    }
cloud_base_url = os.environ["DIGUA_CONFIG_CLOUD_BASE_URL"].strip()
cloud_model = os.environ["DIGUA_CONFIG_CLOUD_MODEL"].strip()
cloud_key_value = os.environ["DIGUA_CONFIG_CLOUD_API_KEY_FILE"]
cloud_key_file = pathlib.Path(cloud_key_value) if cloud_key_value else None
cloud_key_present = bool(os.environ.get("DIGUA_CLOUD_API_KEY")) or bool(cloud_key_file and cloud_key_file.is_file())
if model_mode == "cloud":
    if not cloud_base_url:
        blockers.append("cloud_base_url_missing")
    elif not cloud_base_url.startswith("https://") and not (bool($ALLOW_INSECURE_CLOUD) and cloud_base_url.startswith("http://")):
        blockers.append("cloud_base_url_requires_https")
    if not cloud_model:
        blockers.append("cloud_model_missing")
    if bool($STRICT) and not cloud_key_present:
        blockers.append("cloud_api_key_missing")
payload = {
    "ok": not blockers,
    "dry_run": bool($DRY_RUN),
    "model_weights_bundled": False,
    "models": models,
    "provider": {
        "mode": model_mode,
        "cloud_base_url": cloud_base_url if model_mode == "cloud" else "",
        "cloud_model": cloud_model if model_mode == "cloud" else "",
        "cloud_api_key_present": cloud_key_present if model_mode == "cloud" else False,
        "cloud_private_raw_egress": False,
    },
    "blockers": blockers,
    "warnings": warnings,
}
print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
PY
)"

if [[ "$DRY_RUN" == "0" && -n "$ENV_OUT" ]]; then
  mkdir -p "$(dirname "$ENV_OUT")"
  DIGUA_MODEL_ENV_OUT="$ENV_OUT" python3 - <<'PY'
import os
from pathlib import Path

names = "DIGUA_MODEL_MODE DIGUA_CLOUD_BASE_URL DIGUA_CLOUD_MODEL DIGUA_CLOUD_API_KEY_FILE DIGUA_ALLOW_INSECURE_CLOUD_ENDPOINT DIGUA_QWEN_MODEL_DIR QWEN25_RUNTIME_BIN QWEN25_RUNTIME_CONFIG QWEN25_RUNTIME_LIB_DIR QWEN25_ACTIVE_HBM_PATH DIGUA_CLIP_MODEL_DIR DIGUA_YOLO_MODEL_PATH DIGUA_OCR_MODEL_DIR DIGUA_ASR_MODEL_DIR".split()
lines = ["# Generated by configure_models.sh; paths only, no model weights."]
for name in names:
    value = os.environ.get(name, "")
    if not value:
        continue
    if "\n" in value or "\x00" in value:
        raise SystemExit(f"unsafe environment value: {name}")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'{name}="{escaped}"')
Path(os.environ["DIGUA_MODEL_ENV_OUT"]).write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
  [[ $? -eq 0 ]] || exit 1
fi

if [[ -n "$JSON_OUT" ]]; then mkdir -p "$(dirname "$JSON_OUT")"; printf '%s\n' "$payload" > "$JSON_OUT"; fi
printf '%s\n' "$payload"
python3 - <<PY
import json, sys
raise SystemExit(0 if json.loads('''$payload''').get('ok') else 1)
PY
